# -*- mode: python ; coding: utf-8 -*-

a = Analysis(['main.py'],
             binaries=[],
             datas=[('agents', 'agents'), ('core', 'core'), ('builder', 'builder'), ('logs', 'logs'), ('templates', 'templates'), ('venv', 'venv'), ('personality.json', '.'), ('launcher_config.json', '.'), ('requirements.txt', '.'), ('sentinel_ai_core.py', '.'), ('pc_commander.py', '.'), ('example.py', '.'), ('launcher.py', '.'), ('logging_config.py', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=None,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=None)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='output',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False,
          windowed=True,
          icon='icon.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='output')
